Update getting_started.md
morsbox/rusrails pull request #438
Opened 2021-03-15 07:25 UTC by avrusanov

Changed in: to inclusion: in validates

2021-03-18 09:38 UTC, mikdiet requested changes

2021-03-18 09:38 UTC, mikdiet commented on source/getting_started.md
> +  validates :status, inclusion: VALID_STATUSES
should be

```suggestion
  validates :status, inclusion: { in: VALID_STATUSES }
```

https://edgeguides.rubyonrails.org/getting_started.html#using-concerns

2021-04-06 20:42 UTC, MariaGitCodeHere commented
Привет! Ошибка на этой странице http://rusrails.ru/getting-started-with-rails
В index не может найти public_count после добавления статусов

2021-05-05 19:56 UTC, mikdiet commented
Я делаю полный перевод для 7.0, неактуально уже

2021-05-05 19:56 UTC, closed without merging