add rails version to migration
morsbox/rusrails pull request #483
Opened 2022-03-02 14:41 UTC by an280420

Добавление версии рельс, чтобы сработали миграции.

2022-03-02 15:07 UTC, mikdiet requested changes

2022-03-02 15:07 UTC, mikdiet commented on README.md
> +	rails db:migrate
Согласен, что этот раздел нужен, но команды неправильные.

Для существующего проекта нужно запускать `rails db:setup` - она просто загрузит схему.

2022-03-02 15:07 UTC, mikdiet commented on db/migrate/20130208225411_create_redirects.rb
> +class CreateRedirects < ActiveRecord::Migration[6.0]
Версию в существующих миграциях менять нельзя, она портит существующую схему БД

2022-03-03 21:03 UTC, an280420 commented on README.md
> +	rails db:migrate
Спасибо. Исправил. Ранее думал, что db:setup просто объединяет две команды create и migrate в одну. Что-то не подумал эту команду использовать. С ней все отлично получается.

2022-03-03 21:04 UTC, an280420 commented on db/migrate/20130208225411_create_redirects.rb
> +class CreateRedirects < ActiveRecord::Migration[6.0]
Ок. Коммит отменил.

2022-03-03 23:38 UTC, merged